FROM scratch

ARG SOURCE_REPOSITORY
ARG SOURCE_REVISION
ARG SOURCE_CREATED

LABEL org.opencontainers.image.source="https://github.com/${SOURCE_REPOSITORY}" \
      org.opencontainers.image.revision="${SOURCE_REVISION}" \
      org.opencontainers.image.created="${SOURCE_CREATED}" \
      org.opencontainers.image.title="${SOURCE_REPOSITORY} SDK bundle" \
      org.opencontainers.image.description="Private multi-language SDK source bundle published through GitHub Packages"

COPY . /opt/ores-sdk/
