name = "zed_validation_consumer"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
zed_validation = { path = "../../.deps/lib-core/validation/gleam" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
