name: rust async client

on:
  pull_request:
    paths:
      - 'clients/rust-async/**'
      - '.github/workflows/rust-async-client.yml'

permissions:
  contents: read

jobs:
  hyper-client:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: clients/rust-async
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30
        with:
          toolchain: 1.98.1
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo check
      - run: cargo test
      - run: cargo clippy -- -D warnings
